export const mainTypes = {
    ADD_TASK: 'ADD TASK',
    COMPLETE_TASK: 'COMPLETE_TASK',
    CHANGE_TASK: 'CHANGE TASK',
    DELETE_TASK: 'DELETE TASK',
    GET_ALL_TASK: 'GET_ALL_TASK',
    IS_FETCHING: 'IS FETCHING',
    ADD_FILE: 'ADD_FILE',
    DELETE_FILE: 'DELETE_FILE',
}